version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: radorderpad-postgres
    ports:
      - "5433:5432"  # host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_MULTIPLE_DATABASES: radorder_main,radorder_phi
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - radorderpad-network

networks:
  radorderpad-network:
    driver: bridge

volumes:
  postgres-data:
